function save_parameters(currDate,pars)

fid=fopen([currDate,'/parameters.txt'],'w');
fprintf( fid, ['$\\epsilon=',regexprep(num2str(pars.epsilon'),'\s+',', '),...
                '$, $\\beta=',regexprep(num2str(pars.beta'),'\s+',', '),...
                '$, $h=',regexprep(num2str(pars.h'),'\s+',', '),...
                '$, $\\alpha=', regexprep(num2str(pars.alpha'),'\s+',', '),...
                '$, $k=',regexprep(num2str(pars.k'),'\s+',', '),...
                '$, $T=',regexprep(num2str(pars.T'),'\s+',', '),...
                '$, $c=',regexprep(num2str(pars.c'),'\s+',', '),...
                '$, $c_\\theta=',regexprep(num2str(pars.c_theta'),'\s+',', '),...
                '$, $\\omega=',regexprep(num2str(pars.omega'),'\s+',', '),...
                '$, $\\delta=',regexprep(num2str(pars.delta'),'\s+',', '),...
                '$, istropy$=',regexprep(num2str(pars.isotropy'),'\s+',', '),...
                '$, $g=',regexprep(num2str(pars.g'),'\s+',', '),'$']);
fclose(fid);
end